-- ============================================================================
-- GTM Automation — consolidated database schema (single-shot install).
-- Generated by squashing all historical migrations into one file.
-- Run via:  python setup_database.py
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('version', '0');


-- ============================================================================
-- 001_initial.sql
-- ============================================================================
-- 001_initial.sql
-- Initial complete schema for GTM Automation.
-- Idempotent: all CREATE statements use IF NOT EXISTS.
-- Migration tracking is handled by setup_database.py via schema_meta.

-- ============================================================================
-- 1. projects
-- ============================================================================
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. icps
-- ============================================================================
CREATE TABLE IF NOT EXISTS icps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,

    name TEXT NOT NULL,
    description TEXT,

    -- JSON arrays stored as TEXT
    target_industries TEXT,
    target_geographies TEXT,
    target_company_sizes TEXT,
    target_revenue_range TEXT,

    target_personas TEXT,
    pain_points TEXT,
    competitors TEXT,
    buying_signals TEXT,
    exclusion_rules TEXT,

    offer_summary TEXT,
    value_proposition TEXT,
    outreach_angle TEXT,

    status TEXT DEFAULT 'active',

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (project_id) REFERENCES projects(id)
);
CREATE INDEX IF NOT EXISTS idx_icps_project_id ON icps(project_id);
CREATE INDEX IF NOT EXISTS idx_icps_status ON icps(status);

-- ============================================================================
-- 3. companies
-- ============================================================================
CREATE TABLE IF NOT EXISTS companies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    name TEXT,
    domain TEXT UNIQUE,
    website_url TEXT,

    linkedin_url TEXT,
    country TEXT,
    city TEXT,
    industry TEXT,
    description TEXT,

    employee_count INTEGER,
    revenue_estimate TEXT,

    ecommerce_platform TEXT,
    tech_stack TEXT,  -- JSON

    status TEXT DEFAULT 'new',

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_domain ON companies(domain);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status);
CREATE INDEX IF NOT EXISTS idx_companies_industry ON companies(industry);

-- ============================================================================
-- 4. company_sources
-- ============================================================================
CREATE TABLE IF NOT EXISTS company_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    company_id INTEGER NOT NULL,
    source_type TEXT NOT NULL,
    source_name TEXT,
    source_url TEXT,

    raw_data TEXT,  -- JSON
    confidence_score REAL,

    discovered_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_company_sources_company_id ON company_sources(company_id);
CREATE INDEX IF NOT EXISTS idx_company_sources_type ON company_sources(source_type);

-- ============================================================================
-- 5. company_enrichment
-- ============================================================================
CREATE TABLE IF NOT EXISTS company_enrichment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    company_id INTEGER NOT NULL,
    provider TEXT NOT NULL,

    industry TEXT,
    employee_count INTEGER,
    revenue_estimate TEXT,
    location TEXT,
    tech_stack TEXT,           -- JSON
    ecommerce_platform TEXT,
    social_links TEXT,         -- JSON

    raw_data TEXT,             -- JSON
    confidence_score REAL,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_company_enrichment_company_id ON company_enrichment(company_id);
CREATE INDEX IF NOT EXISTS idx_company_enrichment_provider ON company_enrichment(provider);

-- ============================================================================
-- 6. contacts
-- ============================================================================
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    company_id INTEGER NOT NULL,

    first_name TEXT,
    last_name TEXT,
    full_name TEXT,

    job_title TEXT,
    normalized_role TEXT,

    email TEXT,
    email_status TEXT,         -- unknown|valid|risky|invalid|catch_all|not_found
    email_confidence REAL,

    linkedin_url TEXT,

    country TEXT,
    city TEXT,

    status TEXT DEFAULT 'new',

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_contacts_company_id ON contacts(company_id);
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_linkedin ON contacts(linkedin_url);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON contacts(status);
CREATE INDEX IF NOT EXISTS idx_contacts_normalized_role ON contacts(normalized_role);

-- ============================================================================
-- 7. contact_sources
-- ============================================================================
CREATE TABLE IF NOT EXISTS contact_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    contact_id INTEGER NOT NULL,
    source_type TEXT NOT NULL,
    source_name TEXT,
    source_url TEXT,

    raw_data TEXT,             -- JSON
    confidence_score REAL,

    discovered_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);
CREATE INDEX IF NOT EXISTS idx_contact_sources_contact_id ON contact_sources(contact_id);

-- ============================================================================
-- 8. contact_enrichment
-- ============================================================================
CREATE TABLE IF NOT EXISTS contact_enrichment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    contact_id INTEGER NOT NULL,
    provider TEXT NOT NULL,

    email TEXT,
    email_status TEXT,
    email_confidence REAL,

    job_title TEXT,
    linkedin_url TEXT,
    phone TEXT,

    raw_data TEXT,             -- JSON

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);
CREATE INDEX IF NOT EXISTS idx_contact_enrichment_contact_id ON contact_enrichment(contact_id);

-- ============================================================================
-- 9. signals
-- A signal can refer to a company, a contact, or both. Tied to an ICP.
-- ============================================================================
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    company_id INTEGER,
    contact_id INTEGER,
    icp_id INTEGER,

    signal_type TEXT NOT NULL, -- competitor_usage|hiring_intent|tech_stack|funding|growth|bad_reviews|manual_note|website_copy|linkedin_activity
    signal_name TEXT,

    description TEXT,
    extracted_text TEXT,
    source_url TEXT,

    strength_score REAL,
    confidence_score REAL,

    detected_by TEXT,
    raw_data TEXT,             -- JSON

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (contact_id) REFERENCES contacts(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id)
);
CREATE INDEX IF NOT EXISTS idx_signals_company_id ON signals(company_id);
CREATE INDEX IF NOT EXISTS idx_signals_contact_id ON signals(contact_id);
CREATE INDEX IF NOT EXISTS idx_signals_icp_id ON signals(icp_id);
CREATE INDEX IF NOT EXISTS idx_signals_company_type ON signals(company_id, signal_type);

-- ============================================================================
-- 10. signal_evidence
-- One signal -> many evidence rows. Used for dedupe and citations in drafts.
-- ============================================================================
CREATE TABLE IF NOT EXISTS signal_evidence (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    signal_id INTEGER NOT NULL,

    evidence_type TEXT,        -- url|html_snippet|api_response|manual|llm_extraction
    source_url TEXT,
    extracted_text TEXT,
    snippet TEXT,

    confidence_score REAL,
    raw_data TEXT,             -- JSON

    fingerprint TEXT,          -- hash for dedupe

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (signal_id) REFERENCES signals(id)
);
CREATE INDEX IF NOT EXISTS idx_signal_evidence_signal_id ON signal_evidence(signal_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_signal_evidence_fingerprint ON signal_evidence(signal_id, fingerprint);

-- ============================================================================
-- 11. lead_candidates
-- Central table: ICP + company + (optional) contact.
-- ============================================================================
CREATE TABLE IF NOT EXISTS lead_candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    project_id INTEGER NOT NULL,
    icp_id INTEGER NOT NULL,
    company_id INTEGER NOT NULL,
    contact_id INTEGER,

    lead_status TEXT DEFAULT 'new',  -- new|scored|qualified|needs_review|ready|exported|contacted|replied|rejected|suppressed

    icp_fit_score REAL,
    signal_score REAL,
    persona_fit_score REAL,
    data_quality_score REAL,
    freshness_score REAL,
    final_score REAL,

    qualification_summary TEXT,
    rejection_reason TEXT,

    ready_for_outreach INTEGER DEFAULT 0,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_project_id ON lead_candidates(project_id);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_icp_id ON lead_candidates(icp_id);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_company_contact ON lead_candidates(company_id, contact_id);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_status ON lead_candidates(lead_status);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_pic_status
    ON lead_candidates(project_id, icp_id, lead_status);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_ready ON lead_candidates(ready_for_outreach);
-- Per the spec: avoid duplicate lead_candidates on (icp_id, company_id, contact_id).
-- SQLite treats NULLs as distinct, so company-only leads must be deduped in code.
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_lead_candidate
    ON lead_candidates(icp_id, company_id, contact_id);

-- ============================================================================
-- 12. lead_research
-- AI-generated research brief per lead.
-- ============================================================================
CREATE TABLE IF NOT EXISTS lead_research (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    lead_candidate_id INTEGER NOT NULL,

    company_summary TEXT,
    fit_reason TEXT,
    likely_problem TEXT,
    outreach_angle TEXT,
    talking_points TEXT,       -- JSON array

    evidence TEXT,             -- JSON array of {type, claim, source_url, confidence}

    ai_model TEXT,
    prompt_version TEXT,
    raw_response TEXT,

    status TEXT DEFAULT 'generated',  -- generated|validated|rejected

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (lead_candidate_id) REFERENCES lead_candidates(id)
);
CREATE INDEX IF NOT EXISTS idx_lead_research_lead_id ON lead_research(lead_candidate_id);

-- ============================================================================
-- 13. email_drafts
-- ============================================================================
CREATE TABLE IF NOT EXISTS email_drafts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    lead_candidate_id INTEGER NOT NULL,

    draft_type TEXT DEFAULT 'first_touch',
    variant TEXT DEFAULT 'A',

    subject TEXT,
    body TEXT,

    personalization_notes TEXT,
    source_evidence TEXT,      -- JSON

    ai_model TEXT,
    prompt_version TEXT,

    quality_score REAL,
    quality_status TEXT DEFAULT 'unchecked',  -- unchecked|passed|failed|needs_review

    approved INTEGER DEFAULT 0,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (lead_candidate_id) REFERENCES lead_candidates(id)
);
CREATE INDEX IF NOT EXISTS idx_email_drafts_lead_id ON email_drafts(lead_candidate_id);
CREATE INDEX IF NOT EXISTS idx_email_drafts_quality_status ON email_drafts(quality_status);
CREATE INDEX IF NOT EXISTS idx_email_drafts_approved ON email_drafts(approved);

-- ============================================================================
-- 14. draft_quality_checks
-- One row per QC check applied to a draft (rule, ai, evidence, etc.).
-- ============================================================================
CREATE TABLE IF NOT EXISTS draft_quality_checks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    email_draft_id INTEGER NOT NULL,

    check_type TEXT NOT NULL,  -- rule|banned_phrase|evidence|ai|length|spam_score
    check_name TEXT,

    passed INTEGER DEFAULT 0,
    score REAL,
    severity TEXT,             -- info|warning|error

    message TEXT,
    details TEXT,              -- JSON

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (email_draft_id) REFERENCES email_drafts(id)
);
CREATE INDEX IF NOT EXISTS idx_draft_quality_checks_draft_id ON draft_quality_checks(email_draft_id);
CREATE INDEX IF NOT EXISTS idx_draft_quality_checks_passed ON draft_quality_checks(passed);

-- ============================================================================
-- 15. campaigns
-- ============================================================================
CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    project_id INTEGER NOT NULL,
    icp_id INTEGER,

    name TEXT NOT NULL,
    channel TEXT DEFAULT 'email',

    provider TEXT,
    external_campaign_id TEXT,

    status TEXT DEFAULT 'draft',

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id)
);
CREATE INDEX IF NOT EXISTS idx_campaigns_project_id ON campaigns(project_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);

-- ============================================================================
-- 16. campaign_events
-- ============================================================================
CREATE TABLE IF NOT EXISTS campaign_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    campaign_id INTEGER,
    lead_candidate_id INTEGER,
    contact_id INTEGER,

    event_type TEXT NOT NULL,  -- sent|opened|clicked|replied|positive_reply|negative_reply|neutral_reply|meeting_booked|bounced|unsubscribed|not_interested
    event_value TEXT,

    reply_text TEXT,
    reply_sentiment TEXT,
    reply_intent TEXT,

    raw_data TEXT,             -- JSON

    occurred_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (campaign_id) REFERENCES campaigns(id),
    FOREIGN KEY (lead_candidate_id) REFERENCES lead_candidates(id),
    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);
CREATE INDEX IF NOT EXISTS idx_campaign_events_campaign_id ON campaign_events(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_events_lead_id ON campaign_events(lead_candidate_id);
CREATE INDEX IF NOT EXISTS idx_campaign_events_contact_id ON campaign_events(contact_id);
CREATE INDEX IF NOT EXISTS idx_campaign_events_type ON campaign_events(event_type);

-- ============================================================================
-- 17. suppression_list
-- ============================================================================
CREATE TABLE IF NOT EXISTS suppression_list (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    suppression_type TEXT NOT NULL,  -- domain|email|company_name|linkedin_url|competitor|customer|unsubscribed|bounced
    value TEXT NOT NULL,

    reason TEXT,
    source TEXT,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_suppression_value ON suppression_list(value);
CREATE INDEX IF NOT EXISTS idx_suppression_type ON suppression_list(suppression_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_suppression_type_value
    ON suppression_list(suppression_type, value);

-- ============================================================================
-- 18. knowledge_items
-- ============================================================================
CREATE TABLE IF NOT EXISTS knowledge_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    project_id INTEGER NOT NULL,
    icp_id INTEGER,

    item_type TEXT NOT NULL,   -- call_transcript|campaign_result|reply_analysis|objection|winning_message|competitor_note|positioning_note|manual_note
    title TEXT,

    content TEXT,
    summary TEXT,

    source_type TEXT,
    source_url TEXT,

    tags TEXT,                 -- JSON array
    importance_score REAL,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_items_project_id ON knowledge_items(project_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_items_icp_id ON knowledge_items(icp_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_items_type ON knowledge_items(item_type);

-- ============================================================================
-- 19. pipeline_runs
-- ============================================================================
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    project_id INTEGER NOT NULL,
    icp_id INTEGER,

    run_type TEXT NOT NULL,    -- company_discovery|company_enrichment|contact_discovery|contact_enrichment|signal_extraction|scoring|draft_generation|full_pipeline|feedback_ingestion
    status TEXT DEFAULT 'running',  -- pending|running|completed|failed|partially_completed|cancelled|skipped

    started_at TEXT DEFAULT CURRENT_TIMESTAMP,
    finished_at TEXT,

    total_processed INTEGER DEFAULT 0,
    total_created INTEGER DEFAULT 0,
    total_failed INTEGER DEFAULT 0,

    config TEXT,               -- JSON snapshot of run config
    error_message TEXT,

    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id)
);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_project_id ON pipeline_runs(project_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status ON pipeline_runs(status);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_run_type ON pipeline_runs(run_type);

-- ============================================================================
-- 20. pipeline_run_steps
-- ============================================================================
CREATE TABLE IF NOT EXISTS pipeline_run_steps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    pipeline_run_id INTEGER NOT NULL,

    module_name TEXT NOT NULL,
    status TEXT DEFAULT 'pending',

    started_at TEXT,
    finished_at TEXT,

    input_count INTEGER DEFAULT 0,
    output_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,

    error_message TEXT,
    result_data TEXT,          -- JSON

    FOREIGN KEY (pipeline_run_id) REFERENCES pipeline_runs(id)
);
CREATE INDEX IF NOT EXISTS idx_pipeline_run_steps_run_id ON pipeline_run_steps(pipeline_run_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_run_steps_status ON pipeline_run_steps(status);

-- ============================================================================
-- 21. module_logs
-- ============================================================================
CREATE TABLE IF NOT EXISTS module_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    pipeline_run_id INTEGER,
    pipeline_run_step_id INTEGER,

    module_name TEXT,
    level TEXT DEFAULT 'info', -- debug|info|warning|error|critical

    message TEXT,
    context TEXT,              -- JSON

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (pipeline_run_id) REFERENCES pipeline_runs(id),
    FOREIGN KEY (pipeline_run_step_id) REFERENCES pipeline_run_steps(id)
);
CREATE INDEX IF NOT EXISTS idx_module_logs_run_id ON module_logs(pipeline_run_id);
CREATE INDEX IF NOT EXISTS idx_module_logs_step_id ON module_logs(pipeline_run_step_id);
CREATE INDEX IF NOT EXISTS idx_module_logs_level ON module_logs(level);

-- ============================================================================
-- 22. export_batches
-- ============================================================================
CREATE TABLE IF NOT EXISTS export_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    project_id INTEGER NOT NULL,
    icp_id INTEGER,
    campaign_id INTEGER,

    name TEXT,
    format TEXT DEFAULT 'csv',         -- csv|instantly_csv|smartlead_csv|json
    destination TEXT DEFAULT 'file',   -- file|instantly|smartlead|api

    file_path TEXT,
    row_count INTEGER DEFAULT 0,

    status TEXT DEFAULT 'pending',     -- pending|generating|completed|failed
    error_message TEXT,

    filters TEXT,                      -- JSON snapshot of selection filters

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,

    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (icp_id) REFERENCES icps(id),
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id)
);
CREATE INDEX IF NOT EXISTS idx_export_batches_project_id ON export_batches(project_id);
CREATE INDEX IF NOT EXISTS idx_export_batches_status ON export_batches(status);

-- ============================================================================
-- 23. export_rows
-- One row per exported lead. Also acts as duplicate-export guard.
-- ============================================================================
CREATE TABLE IF NOT EXISTS export_rows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    export_batch_id INTEGER NOT NULL,
    lead_candidate_id INTEGER NOT NULL,
    email_draft_id INTEGER,

    email TEXT,
    payload TEXT,              -- JSON: full exported row

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (export_batch_id) REFERENCES export_batches(id),
    FOREIGN KEY (lead_candidate_id) REFERENCES lead_candidates(id),
    FOREIGN KEY (email_draft_id) REFERENCES email_drafts(id)
);
CREATE INDEX IF NOT EXISTS idx_export_rows_batch_id ON export_rows(export_batch_id);
CREATE INDEX IF NOT EXISTS idx_export_rows_lead_id ON export_rows(lead_candidate_id);
CREATE INDEX IF NOT EXISTS idx_export_rows_email ON export_rows(email);

-- ============================================================================
-- Schema version bump
-- ============================================================================
INSERT INTO schema_meta (key, value, updated_at)
VALUES ('version', '1', CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP;

-- ============================================================================
-- 002_icp_fields.sql
-- ============================================================================
-- Migration 002 — add ICP fields used by the ICP module (File 05).
-- Adds explicit role/seniority/company-size-range columns on icps.
-- Idempotent via tracker; columns added with safe defaults.

ALTER TABLE icps ADD COLUMN target_roles TEXT;
ALTER TABLE icps ADD COLUMN target_seniorities TEXT;
ALTER TABLE icps ADD COLUMN target_company_size_min INTEGER;
ALTER TABLE icps ADD COLUMN target_company_size_max INTEGER;

UPDATE schema_meta SET value = '2', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 003_lead_scoring_fields.sql
-- ============================================================================
-- Migration 003 — add lead-scoring fields used by File 12 (Lead Scoring MVP).
-- fit_score → existing icp_fit_score; intent_score → existing signal_score;
-- combined_score → existing final_score. New columns below.

ALTER TABLE lead_candidates ADD COLUMN priority_tier TEXT;
ALTER TABLE lead_candidates ADD COLUMN scored_at TEXT;
ALTER TABLE lead_candidates ADD COLUMN scoring_explanation TEXT;

CREATE INDEX IF NOT EXISTS idx_lead_candidates_tier ON lead_candidates(project_id, priority_tier);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_final ON lead_candidates(project_id, final_score);

UPDATE schema_meta SET value = '3', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 004_outreach_messages.sql
-- ============================================================================
-- Migration 004 — outreach_messages table for File 13 (Outreach Generation MVP).
-- One row per generated draft. New regenerations create a new row; previous
-- drafts remain as history. status: draft|approved|sent.

CREATE TABLE IF NOT EXISTS outreach_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lead_id INTEGER NOT NULL,
    channel TEXT NOT NULL DEFAULT 'email',
    subject TEXT,
    body TEXT,
    body_html TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    model TEXT,
    prompt TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    context TEXT,         -- JSON: top_signals, matched_criteria, etc
    raw_response TEXT,    -- JSON: raw LLM payload for traceability
    generated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    approved_at TEXT,
    sent_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lead_id) REFERENCES lead_candidates(id)
);

CREATE INDEX IF NOT EXISTS idx_outreach_lead ON outreach_messages(lead_id);
CREATE INDEX IF NOT EXISTS idx_outreach_status ON outreach_messages(status);
CREATE INDEX IF NOT EXISTS idx_outreach_generated ON outreach_messages(generated_at);

UPDATE schema_meta SET value = '4', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 005_quality_checks.sql
-- ============================================================================
-- Migration 005 — quality_checks table for File 14 (Quality Control + Send-Ready Gate MVP).
-- One row per QualityChecker.check() invocation against an outreach_message.
-- rule_results: JSON list of {rule, passed, reason, severity, weight}.

CREATE TABLE IF NOT EXISTS quality_checks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    outreach_message_id INTEGER NOT NULL,
    checker TEXT NOT NULL,
    score REAL NOT NULL DEFAULT 0,
    passed INTEGER NOT NULL DEFAULT 0,
    rule_results TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outreach_message_id) REFERENCES outreach_messages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_quality_checks_msg ON quality_checks(outreach_message_id);
CREATE INDEX IF NOT EXISTS idx_quality_checks_passed ON quality_checks(passed);
CREATE INDEX IF NOT EXISTS idx_quality_checks_score ON quality_checks(score);
CREATE INDEX IF NOT EXISTS idx_quality_checks_created ON quality_checks(created_at);

UPDATE schema_meta SET value = '5', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 006_outreach_sends.sql
-- ============================================================================
-- Migration 006 — outreach_sends table for File 15 (Sender Integration / Send Queue MVP).
-- One row per send attempt against an outreach_message.
-- raw_response: JSON dict from the EmailSender provider.

CREATE TABLE IF NOT EXISTS outreach_sends (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    outreach_message_id INTEGER NOT NULL,
    provider TEXT NOT NULL,
    message_id_external TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    attempted_at TEXT DEFAULT CURRENT_TIMESTAMP,
    sent_at TEXT,
    error_message TEXT,
    raw_response TEXT,
    FOREIGN KEY (outreach_message_id) REFERENCES outreach_messages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_outreach_sends_msg ON outreach_sends(outreach_message_id);
CREATE INDEX IF NOT EXISTS idx_outreach_sends_status ON outreach_sends(status);
CREATE INDEX IF NOT EXISTS idx_outreach_sends_attempted ON outreach_sends(attempted_at);
CREATE INDEX IF NOT EXISTS idx_outreach_sends_sent ON outreach_sends(sent_at);

UPDATE schema_meta SET value = '6', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 007_outreach_replies.sql
-- ============================================================================
-- Migration 007 — outreach_replies table for File 16 (Reply Tracking + Auto-Reply Classification MVP).
-- One row per inbound reply, optionally linked to the originating outreach_send.
-- raw_response: JSON dict from the ingestor / classifier.

CREATE TABLE IF NOT EXISTS outreach_replies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    outreach_message_id INTEGER NOT NULL,
    outreach_send_id INTEGER,
    provider TEXT,
    message_id_external TEXT,
    in_reply_to TEXT,
    from_email TEXT,
    from_name TEXT,
    subject TEXT,
    body TEXT,
    body_html TEXT,
    intent TEXT,
    confidence REAL,
    classifier TEXT,
    raw_response TEXT,
    received_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outreach_message_id) REFERENCES outreach_messages(id) ON DELETE CASCADE,
    FOREIGN KEY (outreach_send_id) REFERENCES outreach_sends(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_outreach_replies_msg ON outreach_replies(outreach_message_id);
CREATE INDEX IF NOT EXISTS idx_outreach_replies_send ON outreach_replies(outreach_send_id);
CREATE INDEX IF NOT EXISTS idx_outreach_replies_intent ON outreach_replies(intent);
CREATE INDEX IF NOT EXISTS idx_outreach_replies_received ON outreach_replies(received_at);

UPDATE schema_meta SET value = '7', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 008_engagement_metrics_cache.sql
-- ============================================================================
-- Migration 008 — engagement_snapshots cache for File 17 (Engagement Metrics + Campaign Dashboard).
-- One row per (project_id, icp_id, window_days) — payload is the full computed metrics dict.

CREATE TABLE IF NOT EXISTS engagement_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    icp_id INTEGER,
    window_days INTEGER NOT NULL,
    computed_at TEXT,
    payload TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE SET NULL,
    UNIQUE(project_id, icp_id, window_days)
);

CREATE INDEX IF NOT EXISTS idx_engagement_snapshots_project ON engagement_snapshots(project_id);
CREATE INDEX IF NOT EXISTS idx_engagement_snapshots_computed ON engagement_snapshots(computed_at);

UPDATE schema_meta SET value = '8', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 009_outreach_experiments.sql
-- ============================================================================
-- Migration 009 — A/B variant testing + multivariate outreach experiments (File 18).

CREATE TABLE IF NOT EXISTS outreach_experiments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    icp_id INTEGER,
    name TEXT NOT NULL,
    hypothesis TEXT,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK(status IN ('draft','running','paused','completed','archived')),
    allocation TEXT NOT NULL DEFAULT 'hash',
    primary_metric TEXT NOT NULL DEFAULT 'positive_reply_rate',
    min_sample_size INTEGER NOT NULL DEFAULT 30,
    confidence_level REAL NOT NULL DEFAULT 0.95,
    started_at TEXT,
    completed_at TEXT,
    winner_variant_id INTEGER,
    config TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS outreach_variants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    experiment_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    weight REAL NOT NULL DEFAULT 1.0,
    subject_template TEXT,
    body_template TEXT,
    cta_template TEXT,
    params TEXT,
    is_control INTEGER NOT NULL DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (experiment_id) REFERENCES outreach_experiments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lead_variant_assignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lead_id INTEGER NOT NULL,
    experiment_id INTEGER NOT NULL,
    variant_id INTEGER NOT NULL,
    assigned_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(lead_id, experiment_id),
    FOREIGN KEY (lead_id) REFERENCES lead_candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (experiment_id) REFERENCES outreach_experiments(id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES outreach_variants(id) ON DELETE CASCADE
);

ALTER TABLE outreach_messages ADD COLUMN variant_id INTEGER REFERENCES outreach_variants(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_outreach_variants_experiment ON outreach_variants(experiment_id);
CREATE INDEX IF NOT EXISTS idx_lva_experiment ON lead_variant_assignments(experiment_id);
CREATE INDEX IF NOT EXISTS idx_lva_lead ON lead_variant_assignments(lead_id);
CREATE INDEX IF NOT EXISTS idx_lva_variant ON lead_variant_assignments(variant_id);
CREATE INDEX IF NOT EXISTS idx_outreach_messages_variant ON outreach_messages(variant_id);
CREATE INDEX IF NOT EXISTS idx_outreach_experiments_project ON outreach_experiments(project_id);
CREATE INDEX IF NOT EXISTS idx_outreach_experiments_status ON outreach_experiments(status);

UPDATE schema_meta SET value = '9', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 010_lead_exports.sql
-- ============================================================================
-- Migration 010 — Lead exports + CRM-ready delivery (File 19).

CREATE TABLE IF NOT EXISTS lead_exports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    icp_id INTEGER,
    name TEXT NOT NULL,
    destination TEXT NOT NULL DEFAULT 'filesystem'
        CHECK(destination IN ('filesystem','hubspot','salesforce')),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','building','ready','delivered','failed')),
    format TEXT NOT NULL DEFAULT 'csv'
        CHECK(format IN ('csv','json')),
    filters TEXT,
    artifact_path TEXT,
    artifact_size_bytes INTEGER,
    row_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    started_at TEXT,
    completed_at TEXT,
    delivered_at TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS lead_export_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lead_export_id INTEGER NOT NULL,
    lead_id INTEGER NOT NULL,
    outreach_message_id INTEGER,
    variant_id INTEGER,
    payload TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(lead_export_id, lead_id),
    FOREIGN KEY (lead_export_id) REFERENCES lead_exports(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES lead_candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (outreach_message_id) REFERENCES outreach_messages(id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES outreach_variants(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_lead_exports_project ON lead_exports(project_id);
CREATE INDEX IF NOT EXISTS idx_lead_exports_status ON lead_exports(status);
CREATE INDEX IF NOT EXISTS idx_lead_export_items_export ON lead_export_items(lead_export_id);
CREATE INDEX IF NOT EXISTS idx_lead_export_items_lead ON lead_export_items(lead_id);

UPDATE schema_meta SET value = '10', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 011_feedback_lifecycle.sql
-- ============================================================================
-- Migration 011 — Feedback events + lifecycle transitions (File 20).

CREATE TABLE IF NOT EXISTS feedback_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    icp_id INTEGER,
    lead_id INTEGER,
    outreach_message_id INTEGER,
    variant_id INTEGER,
    source TEXT NOT NULL
        CHECK(source IN ('human','reply','crm_sync','export_delivered','system')),
    kind TEXT NOT NULL
        CHECK(kind IN ('thumbs_up','thumbs_down','lead_qualified','lead_disqualified',
                       'meeting_booked','won','lost','unsubscribe','note')),
    payload TEXT,
    weight REAL DEFAULT 1.0,
    applied INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE SET NULL,
    FOREIGN KEY (lead_id) REFERENCES lead_candidates(id) ON DELETE SET NULL,
    FOREIGN KEY (outreach_message_id) REFERENCES outreach_messages(id) ON DELETE SET NULL,
    FOREIGN KEY (variant_id) REFERENCES outreach_variants(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS lifecycle_transitions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lead_id INTEGER NOT NULL,
    from_status TEXT,
    to_status TEXT NOT NULL,
    reason TEXT,
    source TEXT,
    feedback_event_id INTEGER,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lead_id) REFERENCES lead_candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (feedback_event_id) REFERENCES feedback_events(id) ON DELETE SET NULL
);

ALTER TABLE lead_candidates ADD COLUMN lifecycle_stage TEXT DEFAULT 'new';

CREATE INDEX IF NOT EXISTS idx_feedback_events_project ON feedback_events(project_id);
CREATE INDEX IF NOT EXISTS idx_feedback_events_kind ON feedback_events(kind);
CREATE INDEX IF NOT EXISTS idx_feedback_events_applied ON feedback_events(applied);
CREATE INDEX IF NOT EXISTS idx_lifecycle_transitions_lead ON lifecycle_transitions(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_candidates_lifecycle ON lead_candidates(lifecycle_stage);

UPDATE schema_meta SET value = '11', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 012_scoring_weight_revisions.sql
-- ============================================================================
-- Migration 012 — Scoring weight revisions (File 21).

CREATE TABLE IF NOT EXISTS scoring_weight_revisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    icp_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    parent_revision_id INTEGER,
    source TEXT NOT NULL
        CHECK(source IN ('manual','auto_tune','rollback')),
    status TEXT NOT NULL DEFAULT 'proposed'
        CHECK(status IN ('proposed','active','archived','rejected')),
    proposed_weights TEXT NOT NULL,
    baseline_weights TEXT,
    contributing_event_ids TEXT,
    stats TEXT,
    notes TEXT,
    created_by TEXT,
    activated_at TEXT,
    archived_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_revision_id) REFERENCES scoring_weight_revisions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_swr_icp ON scoring_weight_revisions(icp_id);
CREATE INDEX IF NOT EXISTS idx_swr_status ON scoring_weight_revisions(icp_id, status);
CREATE INDEX IF NOT EXISTS idx_swr_created ON scoring_weight_revisions(created_at);

UPDATE schema_meta SET value = '12', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 013_pipeline_templates.sql
-- ============================================================================
-- Migration 013 — Pipeline templates + schedules + per-run summary (File 22).

ALTER TABLE pipeline_runs ADD COLUMN summary TEXT;

CREATE TABLE IF NOT EXISTS pipeline_templates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK(status IN ('draft','active','archived')),
    steps TEXT NOT NULL,
    notes TEXT,
    created_by TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pt_project ON pipeline_templates(project_id);
CREATE INDEX IF NOT EXISTS idx_pt_slug ON pipeline_templates(slug);
CREATE INDEX IF NOT EXISTS idx_pt_status ON pipeline_templates(status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pt_project_slug_version
    ON pipeline_templates(COALESCE(project_id, 0), slug, version);

CREATE TABLE IF NOT EXISTS pipeline_schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    template_id INTEGER NOT NULL,
    icp_id INTEGER,
    name TEXT NOT NULL,
    cron_expr TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    enabled INTEGER NOT NULL DEFAULT 1,
    last_fired_at TEXT,
    next_fire_at TEXT,
    last_run_id INTEGER,
    notes TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (template_id) REFERENCES pipeline_templates(id) ON DELETE CASCADE,
    FOREIGN KEY (icp_id) REFERENCES icps(id) ON DELETE SET NULL,
    FOREIGN KEY (last_run_id) REFERENCES pipeline_runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ps_project ON pipeline_schedules(project_id);
CREATE INDEX IF NOT EXISTS idx_ps_template ON pipeline_schedules(template_id);
CREATE INDEX IF NOT EXISTS idx_ps_enabled_next ON pipeline_schedules(enabled, next_fire_at);

-- Seed built-in standard_v1 (project_id NULL = global default).
INSERT INTO pipeline_templates (project_id, name, slug, version, status, steps, notes, created_by)
SELECT NULL, 'Standard v1', 'standard_v1', 1, 'active',
    '[{"run_type":"company_discovery","config":{},"on_failure":"continue"},' ||
    '{"run_type":"company_enrichment","config":{},"on_failure":"continue"},' ||
    '{"run_type":"contact_discovery","config":{},"on_failure":"continue"},' ||
    '{"run_type":"contact_enrichment","config":{},"on_failure":"continue"},' ||
    '{"run_type":"signal_extraction","config":{},"on_failure":"continue"},' ||
    '{"run_type":"lead_scoring","config":{},"on_failure":"continue"},' ||
    '{"run_type":"quality_control","config":{},"on_failure":"continue"},' ||
    '{"run_type":"outreach_generation","config":{},"on_failure":"continue"},' ||
    '{"run_type":"suppression","config":{},"on_failure":"continue"},' ||
    '{"run_type":"send_queue","config":{},"on_failure":"continue"},' ||
    '{"run_type":"reply_tracking","config":{},"on_failure":"continue"},' ||
    '{"run_type":"experiment_scoring","config":{},"on_failure":"continue"},' ||
    '{"run_type":"export","config":{},"on_failure":"skip"},' ||
    '{"run_type":"feedback_ingestion","config":{},"on_failure":"continue"},' ||
    '{"run_type":"weight_tuning","config":{"auto_promote":false},"on_failure":"skip"}]',
    'Built-in default end-to-end pipeline.', 'system'
WHERE NOT EXISTS (SELECT 1 FROM pipeline_templates WHERE slug='standard_v1' AND version=1);

UPDATE schema_meta SET value = '13', updated_at = CURRENT_TIMESTAMP WHERE key = 'version';

-- ============================================================================
-- 014_conversation_layer.sql
-- ============================================================================
-- Migration 014 — AI Reasoning Memory + Conversation Threads (File 23).

-- ── decision_traces ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS decision_traces (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    pipeline_run_id  INTEGER,
    step_index       INTEGER,
    module_name      TEXT NOT NULL DEFAULT '',
    lead_id          INTEGER,
    contact_id       INTEGER,
    decision_type    TEXT NOT NULL
        CHECK(decision_type IN ('score','draft','quality','send','reply','tuning','thread')),
    input_snapshot   TEXT,          -- JSON
    rationale        TEXT,
    model_name       TEXT,
    tokens_in        INTEGER,
    tokens_out       INTEGER,
    confidence       REAL,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S','now')),
    FOREIGN KEY (pipeline_run_id) REFERENCES pipeline_runs(id) ON DELETE SET NULL,
    FOREIGN KEY (lead_id)        REFERENCES lead_candidates(id) ON DELETE SET NULL,
    FOREIGN KEY (contact_id)     REFERENCES contacts(id)        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_dt_run      ON decision_traces(pipeline_run_id);
CREATE INDEX IF NOT EXISTS idx_dt_lead     ON decision_traces(lead_id);
CREATE INDEX IF NOT EXISTS idx_dt_contact  ON decision_traces(contact_id);
CREATE INDEX IF NOT EXISTS idx_dt_type     ON decision_traces(decision_type);
CREATE INDEX IF NOT EXISTS idx_dt_created  ON decision_traces(created_at DESC);

-- ── lead_threads ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_threads (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id       INTEGER NOT NULL,
    icp_id           INTEGER,
    lead_id          INTEGER,
    contact_id       INTEGER,
    subject          TEXT,
    status           TEXT NOT NULL DEFAULT 'open'
        CHECK(status IN ('open','awaiting_reply','replied','closed','bounced')),
    last_message_at  TEXT,
    last_direction   TEXT CHECK(last_direction IN ('out','in',NULL)),
    message_count    INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S','now')),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S','now')),
    FOREIGN KEY (project_id) REFERENCES projects(id)        ON DELETE CASCADE,
    FOREIGN KEY (icp_id)     REFERENCES icps(id)            ON DELETE SET NULL,
    FOREIGN KEY (lead_id)    REFERENCES lead_candidates(id) ON DELETE SET NULL,
    FOREIGN KEY (contact_id) REFERENCES contacts(id)        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_lt_project   ON lead_threads(project_id);
CREATE INDEX IF NOT EXISTS idx_lt_lead      ON lead_threads(lead_id);
CREATE INDEX IF NOT EXISTS idx_lt_contact   ON lead_threads(contact_id);
CREATE INDEX IF NOT EXISTS idx_lt_status    ON lead_threads(status);
CREATE INDEX IF NOT EXISTS idx_lt_last_msg  ON lead_threads(last_message_at DESC);

-- ── lead_thread_messages ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_thread_messages (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    thread_id           INTEGER NOT NULL,
    direction           TEXT NOT NULL CHECK(direction IN ('out','in')),
    source              TEXT NOT NULL DEFAULT 'manual'
        CHECK(source IN ('outreach_send','outreach_reply','manual','reply_draft')),
    external_id         TEXT,
    send_id             INTEGER,
    reply_id            INTEGER,
    draft_id            INTEGER,
    subject             TEXT,
    body_text           TEXT,
    body_html           TEXT,
    sent_at             TEXT,
    received_at         TEXT,
    headers             TEXT,           -- JSON
    attachments         TEXT,           -- JSON
    raw_data            TEXT,           -- JSON
    decision_trace_id   INTEGER,
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%S','now')),
    FOREIGN KEY (thread_id)          REFERENCES lead_threads(id)          ON DELETE CASCADE,
    FOREIGN KEY (send_id)            REFERENCES outreach_sends(id)        ON DELETE SET NULL,
    FOREIGN KEY (reply_id)           REFERENCES outreach_replies(id)      ON DELETE SET NULL,
    FOREIGN KEY (draft_id)           REFERENCES outreach_messages(id)     ON DELETE SET NULL,
    FOREIGN KEY (decision_trace_id)  REFERENCES decision_traces(id)       ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ltm_thread     ON lead_thread_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_ltm_send       ON lead_thread_messages(send_id);
CREATE INDEX IF NOT EXISTS idx_ltm_reply      ON lead_thread_messages(reply_id);
CREATE INDEX IF NOT EXISTS idx_ltm_direction  ON lead_thread_messages(thread_id, direction);

-- Bump schema version
UPDATE schema_meta SET value = '14' WHERE key = 'version';

-- ============================================================================
-- 015_auth.sql
-- ============================================================================
-- Migration 015 — Auth layer (File 24).
-- users:           credentials + role
-- project_members: per-project access (owner|admin|member|viewer)
-- audit_log:       structured request/event log (optional sink)

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    is_active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS project_members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members(user_id);
CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members(project_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    project_id INTEGER,
    action TEXT NOT NULL,
    resource TEXT,
    resource_id INTEGER,
    method TEXT,
    path TEXT,
    status_code INTEGER,
    ip_address TEXT,
    user_agent TEXT,
    metadata TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_project ON audit_log(project_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);

UPDATE schema_meta SET value = '15' WHERE key = 'version';
